---
- name: install PHP 8.1 with required packages
  hosts: test
  become: yes
  tasks:
    - name: "Repo PHP 8.1"
      apt_repository:
        repo="ppa:ondrej/php"
   
    - name: "Updating the repo"
      apt: update_cache=yes

    - name: Install PHP 8.1
      apt: name=php8.1 state=present

    - name: install required packages
      apt:
        pkg:
          - php8.1-cli
          - php8.1-common
          - php8.1-mysql
          - php8.1-zip
          - php8.1-gd
          - php8.1-mbstring
          - php8.1-curl
          - php8.1-xml
          - php8.1-bcmath
          - php8.1-fpm
          - php8.1-intl
          - php8.1-soap
        state: present
        update_cache: yes

    - name: restart php8.1-fpm
      service: name=php8.1-fpm state=restarted
